### PR TITLE
Add test coverage for localized paths

### PR DESCRIPTION
**Pull request by nirvn**
Ideally we'd also test it on the QFieldCloud side of things, but this is already better than zero coverage.

### CODE REVIEW

**Review by suricactus — APPROVED** [review]
Great move!

**Comment by suricactus** [comment]
NOTE before merging, `isort` failed.

**Comment by nirvn** [comment]
@suricactus , I've jumped onto the next version of Ubuntu and I'm stumbling on pre commit error with isort :/

**Comment by suricactus** [comment]
@nirvn I have fixed the linting issue and added a bit more testing for the `is_localized_path`.

**Comment by nirvn** [comment]
@suricactus , nice thanks.

**Comment by nirvn** [comment]
I can't approve this since I opened the PR but +1 to ask changes @suricactus

**Pull request merged**
