### PR TITLE
Fix ASCII filename check and some providers encoding check

### PR DESCRIPTION
**Pull request by suricactus**

### CODE REVIEW

**Comment by mbernasocchi** [comment]
Task linked: [DEV-3157 Fix checks for ASCII filename](https://app.clickup.com/t/2192114/DEV-3157)

**Comment by mbernasocchi** [comment]
Task linked: [DEV-3158 Fix checks for encoding for PostGIS provider, it returns empty string](https://app.clickup.com/t/2192114/DEV-3158)

**Review by nirvn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Is this included in beta15?
We had a similar problem

**Comment by m-kuhn** [comment]
Just checked the dataprovider encoding which is `''`

**Comment by m-kuhn** [comment]
Is this included in beta15?

We had a warning that the `layer is not 'UTF-8' but ""` for a postgis layer.
Running `iface.activeLayer().dataProvider().encoding()` returned `''`

**Comment by m-kuhn** [comment]
Small additional information, the warning is shown in a loop for each layer, which is quite a lot of clicks for 30 layers :-)

**Comment by suricactus** [comment]
Already fixed this here https://github.com/opengisch/libqfieldsync/commit/3b40a44b76b1f36683af4c9a3f544b22dbc0d0f6

**Pull request merged**
